Update 0-custom_http_response_header

diff --git a/load_balancer/0-custom_http_response_header b/load_balancer/0-custom_http_response_header
--- a/load_balancer/0-custom_http_response_header
+++ b/load_balancer/0-custom_http_response_header
@@ -1,32 +1,22 @@
 #!/usr/bin/env bash
-# comment 
-# inspired from https://stackoverflow.com/questions/22306006/configuration-file-etc-nginx-nginx-conf-test-failed-how-do-i-know-why-this-h
-sudo apt remove --purge nginx nginx-full nginx-common -y
+#This script automates stuff
+
+# Update package list and install Nginx
 sudo apt update
-sudo apt install nginx -y
-sudo touch /var/www/html/index.html
+sudo apt install -y nginx
 
-echo "Holberton School" | sudo tee /var/www/html/index.html
-sudo touch /var/www/html/error404.html
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
+# Retrieve the hostname of the server
+HOSTNAME=$(hostname)
 
-printf %s 'server {
-        listen 80 default_server;
-        listen [::]:80 default_server;
+# Configure Nginx to add the custom HTTP header "X-Served-By"
+# This inserts the custom header in the default server block configuration
+sudo sed -i "/server {/a \    add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
 
-        root /var/www/html;
-
-        index index.html;
-        error_page 404 /error404.html;
-
-        server_name _;
-        
-        add_header X-Served-By $hostname;
-        
-        location /redirect_me {
-           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
-        }
-}
-' | sudo tee /etc/nginx/sites-available/default
-
-sudo service nginx restart
+# Test Nginx configuration and reload to apply changes
+if sudo nginx -t; then
+    sudo systemctl reload nginx
+    echo "Nginx configured with custom header X-Served-By: $HOSTNAME"
+else
+    echo "Nginx configuration test failed. Please check the configuration."
+    exit 1
+fi
