Update 3-redirection

diff --git a/web_server/3-redirection b/web_server/3-redirection
--- a/web_server/3-redirection
+++ b/web_server/3-redirection
@@ -1,8 +1,22 @@
 #!/usr/bin/env bash
-# Configure your Nginx server so that /redirect_me is redirecting to another page.
-apt-get update
-apt-get -y install nginx
-ufw allow 'Nginx HTTP'
-echo "Hoberlton School" > /var/www/html/index.nginx-debian.html
-sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
-service nginx start
+# This file contains a script that redirects a request
+
+# Update package list and install Nginx
+sudo apt update
+sudo apt install -y nginx
+
+# Define the URL to redirect to
+REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"
+
+# Configure Nginx to add a 301 redirection from /redirect_me
+# We use sed to insert the redirection configuration in the default server block
+sudo sed -i '/server {/a \    location = /redirect_me {\n        return 301 '"$REDIRECT_URL"';\n    }' /etc/nginx/sites-available/default
+
+# Test the Nginx configuration and reload to apply changes
+if sudo nginx -t; then
+    sudo systemctl reload nginx
+    echo "Configuration complete. /redirect_me now redirects to $REDIRECT_URL with a 301 status."
+else
+    echo "Nginx configuration test failed. Please check the configuration."
+    exit 1
+fi
